/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformLayoutRouteRouteImport } from './routes/_platform-layout/route'
import { Route as PlatformLayoutIndexRouteImport } from './routes/_platform-layout/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const PlatformLayoutRouteRoute = PlatformLayoutRouteRouteImport.update({
  id: '/_platform-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLayoutIndexRoute = PlatformLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformLayoutRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/$': typeof ApiSplatRoute
  '/': typeof PlatformLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/': typeof PlatformLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_platform-layout': typeof PlatformLayoutRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_platform-layout/': typeof PlatformLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/$' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/$' | '/'
  id: '__root__' | '/_platform-layout' | '/api/$' | '/_platform-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlatformLayoutRouteRoute: typeof PlatformLayoutRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform-layout': {
      id: '/_platform-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PlatformLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform-layout/': {
      id: '/_platform-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlatformLayoutIndexRouteImport
      parentRoute: typeof PlatformLayoutRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlatformLayoutRouteRouteChildren {
  PlatformLayoutIndexRoute: typeof PlatformLayoutIndexRoute
}

const PlatformLayoutRouteRouteChildren: PlatformLayoutRouteRouteChildren = {
  PlatformLayoutIndexRoute: PlatformLayoutIndexRoute,
}

const PlatformLayoutRouteRouteWithChildren =
  PlatformLayoutRouteRoute._addFileChildren(PlatformLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PlatformLayoutRouteRoute: PlatformLayoutRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
